### ISSUE TITLE
script doesn't run

### ISSUE THREAD

**Issue by thob** [martinseener/Hebato#8]
If I try to run the script nothing happens. I put it in /root/.scripts (I'm on Linux Mint 17.3). Any idea what I'm missing?

**Comment by martinseener** [comment]
Hi @thob,

can you tell me what you exactly did in order to run the script? Since it's a bash script you might want to give it execute rights first using `chmod +x hebato.sh` and then run it with `./hebato.sh` or `/root/.scripts/hebato.sh`.

Also you first need to change the configuration within the file to reflect your credentials and what you want to backup.

I also made no changes for some time now but i still maintain it, because it's still in use at mine, so if anything doesn't work, just tell me or open a new more specific issue.

I may do some more rework of Hebato the next weeks!

Thanks for using it and giving me feedback!

**Comment by thob** [comment]
I did all that except I set the x via the GUi. Will try it via cli.

**Comment by thob** [comment]
OK: seems the dependency check missed out on sshfs. After I installed it the script works now but  
- for some reason I has troubles reading the public key and asks for the pwd  
- the mounted drives are not accessible for I'm no root

**Comment by martinseener** [comment]
@thob how can it be, that the script missed out on sshfs? The dependency is there and should be checked and if it's not there, it should exit with an appropriate error. Can you tell me a bit more about the OS you're using so i can double check on that?
* what you exactly mean with troubles reading the pub key?
* yeah you have to run it as root. i've never tried it really without root because mounting stuff should be done as root. Can you try it with root? I may add support for non-root users possibly later. You could also add an issue for that as well!

**Comment by thob** [comment]
* after I installed sshfs the script worked, that's the only thing I can say _(it never prompted me to do anything and gave no error message before)_  
* it seems it can't read the key and asks for a password  
* this one is minor but in order to open the drive I need to open it as root  

I'm on Linux Mint 17.3 (Ubuntu 14.04)

**Comment by martinseener** [comment]
Thanks for reporting back! I'll try to find the problems and fix them soon! I hope it works now for you?

**Comment by martinseener** [comment]
I'm sorry, i stopped maintaining Hebato in favor of other/better tools.
